### ISSUE TITLE
BoxTextured model uses invalid texture/wrapping combo

### ISSUE THREAD

**Issue by msfeldstein** [KhronosGroup/glTF-Sample-Models#135] opened 2017-11-30 03:01 UTC
The texture in BoxTextured example is a non-Power Of Two texture (211x211) and the wrap mode is REPEAT.  Most implementations of opengl won't render this properly.  Technically this isn't an invalid model, but it could confuse people as to why it's not working if they don't resize their textures before GPU-upload.  Should we resize the texture to 256, or should we just put a note in there that this is a model that hits some edge cases that a renderer might not support?

**Comment by msfeldstein** [comment] 2017-11-30 03:12
For example if you don't resize the texture on ios it renders as black

**Comment by pjcozzi** [comment] 2017-12-01 01:19
Resizing to 256 sounds good to me - the Cesium team made this model and we did not intentionally pick NPOT and REPEAT - it was probably an old exporter or converter issue.

Would you be able to contribute the fix?

**Comment by emackey** [comment] 2017-12-01 01:21
Do we need to update the spec or the validator to disallow this, or warn on this?

**Comment by pjcozzi** [comment] 2017-12-01 01:22
> Do we need to update the spec or the validator to disallow this, or warn on this?

+1

@lexaknyazev?

**Comment by bghgary** [comment] 2017-12-01 01:35
Last implementation note of https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#samplers?

**Comment by pjcozzi** [comment] 2017-12-01 01:39
Ah, actually I am pretty sure that I wrote that!

**Comment by emackey** [comment] 2017-12-01 01:54
Hm.  If I'm reading that right, it's the engine's responsibility to resize the texture as needed.  So maybe the sample model should stay, and the engines get fixed?  I feel like that runs counter to our usual advice, of the toolchain getting the model into the best shape possible for the runtime.

**Comment by pjcozzi** [comment] 2017-12-01 01:57
@emackey that is what I said years ago when we designed this, but the problem is that the toolchain might have to waste a lot of space with padding, e.g., 257 -> 512.

**Comment by msfeldstein** [comment] 2017-12-01 01:58
I have a pull request up that 'fixes' this and also adds an explicit
NonPowerOfTwo example so that people don't get tripped up but also have a
full coverage of the problem

**Comment by msfeldstein** [comment] 2017-12-01 01:59
https://github.com/KhronosGroup/glTF-Sample-Models/pull/137

**Comment by lexaknyazev** [comment] 2017-12-01 13:31
@pjcozzi 
>  the toolchain might have to waste a lot of space with padding, e.g., 257 -> 512.

Padding (and rewriting UVs) is one option, the other is to rescale the image. Toolchains may have some flexibility.

@emackey 
Validator issues an `Info` on NPOT images.

@msfeldstein 
> Most implementations of opengl won't render this properly.

According to specs, only OpenGL ES 2.0 has limitations regarding NPOT textures. 
Are you saying that real-world ES 3.0+ or desktop implementations have the same issue?

**Comment by msfeldstein** [comment] 2017-12-01 16:23
Perhaps "most" was an overstatement.  My iPhone 6s fails with it, though it is using OpenGLES20, i will test if i have the same problem if i request OpenGLES3.0

**Comment by emackey** [comment] 2018-03-01 21:12
This issue was resolved in #137, thanks @msfeldstein.

**Closed by emackey** 2018-03-01 21:12 UTC
Labels: bug
