### ISSUE TITLE
According to the specs, TriangleWithoutIndices should not render anything

### ISSUE THREAD

**Issue by Raveler** [KhronosGroup/glTF-Sample-Models#240] opened 2019-12-04 11:33 UTC
The specs say this about a gltf-file without a scene-field specified:

> When scene is undefined, runtime is not required to render anything at load time.
> Implementation Note: This allows applications to use glTF assets as libraries of individual entities such as materials or meshes.

Since TriangleWithoutIndices does not specify a scene, the default rendered view should be empty, right?

**Comment by emackey** [comment] 2019-12-04 14:20
I read that "not required to render" as being also not prevented from rendering.  It would be permissible to show a blank screen, but it would be equally permissible to treat the file's first scene as the default scene automatically.

The scene list is an area of the spec that could use some clarification.  For example: https://github.com/KhronosGroup/glTF/issues/1542 and https://github.com/KhronosGroup/glTF/issues/1547

For the sample repo, perhaps we should just fix the sample model to name the correct scene?

**Comment by javagl** [comment] 2019-12-04 15:53
This is related to (or basically a duplicate of) https://github.com/KhronosGroup/glTF-Sample-Models/issues/166 - OK, that was my responsibility. I'll re-insert this into my TODO list with higher priority (and leave this issue open until it's *really* done). Sorry about that.

**Comment by Raveler** [comment] 2019-12-05 08:15
Alright, thanks! I know it's total nitpicking but those simple models are all used to pick up very detailed flaws in the implementation, so people implementing glTF might think this is such a corner case being tested :).

**Closed** 2019-12-11 22:53 UTC
