### ISSUE TITLE
riggedSimple has noop animation channels

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF-Sample-Models#204] opened 2018-12-04 05:06 UTC
There are translation and scale targets which are animated but the values actually stay constant, and therefore do not need to be animated. This is probably the result of automated conversion. The example should be simplified as it aims to be simple.

**Comment by lexaknyazev** [comment] 2018-12-04 05:12
Duplicate of #86.

**Closed** 2018-12-04 12:04 UTC
