### ISSUE TITLE
Missing license for VertexColorTest

### ISSUE THREAD

**Issue by aidinabedi** [KhronosGroup/glTF-Sample-Models#370] opened 2023-01-30 15:34 UTC
What's the license information for [VertexColorTest](/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VertexColorTest)?

**Comment by javagl** [comment] 2023-01-30 18:06
To avoid having too many issues open, I'll close this one as duplicate of https://github.com/KhronosGroup/glTF-Sample-Models/issues/227 (and leave a comment there)

**Closed by javagl** 2023-01-30 18:06 UTC
